[tools]
lua = "latest"
neovim = "latest"
node = "24"
go = "latest"
deno = "latest"
bun = "latest"
"npm:httpyac" = "latest"
"npm:vercel" = "latest"
claude-code = "latest"
lazygit = "latest"
lazydocker = "latest"
"aqua:fish-shell/fish-shell" = "latest"
bitwarden = "latest"
zoxide = "latest"
bat = "latest"
"cargo:eza" = "latest"
"cargo:tlrc" = "latest"
"npm:@botpress/cli" = "latest"
"npm:ts-node" = "latest"
"npm:typescript" = "latest"
"npm:ngrok" = "latest"
